version: 2.1
orbs:
  node: circleci/node@4.7.0
workflows:
  run-npm-command:
    jobs:
      - node/run:
          yarn-run: components:generate
  tests:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 'lts'
                - '12.22'
              run-command:
                - 'test:unit'
                - 'test:e2e --headless'
          pkg-manager: yarn
