version: 2.1
orbs:
  node: circleci/node@4.7.0
  cypress: cypress-io/cypress@1.29.0
jobs:
  unit:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn components:generate
      - run:
          command: yarn test:unit
  e2e:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn      
          cache-version: v2
      - run:
          command: yarn components:generate
      - run:
          command: yarn test:e2e --headless
workflows:
  test_my_app:
    jobs:
      - unit
  example-workflow:
    jobs:
      - cypress/run:
          yarn: true
          post-install:
            - run: yarn components:generate